
ALL: SYSPTR.EXE SYSPTR.RES .symbolic
   @%null


SYSPTR.EXE: SYSPTR.OBJ SYSPTR.RES SYSPTR.DLG SYSPTR.MAK
   WLINK @SYSPTR.LNK
   RC -p -x SYSPTR.RES SYSPTR.EXE

SYSPTR.res:  SYSPTR.rc SYSPTR.h SYSPTR.DLG
   RC -r SYSPTR.RC SYSPTR.RES
   
SYSPTR.OBJ: SYSPTR.CPP SYSPTR.H
    WPP386 -s -bm -ox SYSPTR.CPP
